services:
  mysql:
    image: mysql:8.0
    container_name: zapquest-mysql
    environment:
      MYSQL_ROOT_PASSWORD: .nnD8axG3w!hrYnxqTEx
      MYSQL_DATABASE: zapquest
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: zapquest-backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/zapquest
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: .nnD8axG3w!hrYnxqTEx
    ports:
      - "8080:8080"

volumes:
  mysql-data:
